# City Bike Data 2018

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np

In [2]:
# Files to Load
march2018 = "201803-citibike-tripdata.csv"
june2018 = "201806-citibike-tripdata.csv"
september2018 = "201809-citibike-tripdata.csv"
december2018 = "201812-citibike-tripdata.csv"

In [3]:
# Read April 2018 Citi Bike Data File & Store into Pandas DataFrame
march2018_df = pd.read_csv(march2018, encoding="ISO-8859-1")
march2018_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,816,2018-03-01 02:29:13.7270,2018-03-01 02:42:50.1460,72,W 52 St & 11 Ave,40.767272,-73.993929,379,W 31 St & 7 Ave,40.749156,-73.991600,31413,Subscriber,1973,1
1,235,2018-03-01 05:12:37.0320,2018-03-01 05:16:32.1010,72,W 52 St & 11 Ave,40.767272,-73.993929,478,11 Ave & W 41 St,40.760301,-73.998842,33202,Subscriber,1965,1
2,1250,2018-03-01 05:45:49.9000,2018-03-01 06:06:39.9080,72,W 52 St & 11 Ave,40.767272,-73.993929,3664,North Moore St & Greenwich St,40.720195,-74.010301,26675,Subscriber,1984,1
3,741,2018-03-01 06:54:19.6150,2018-03-01 07:06:40.9790,72,W 52 St & 11 Ave,40.767272,-73.993929,459,W 20 St & 11 Ave,40.746745,-74.007756,31011,Subscriber,1981,1
4,727,2018-03-01 07:08:38.8610,2018-03-01 07:20:46.8500,72,W 52 St & 11 Ave,40.767272,-73.993929,2006,Central Park S & 6 Ave,40.765909,-73.976342,30616,Subscriber,1990,2

In [4]:
march2018_df = march2018_df.rename(columns={"tripduration": "Trip Duration",
                                            "starttime": "Start Time",
                                            "stoptime": "Stop Time",
                                            "start station id": "Start Station ID",
                                            "start station name": "Start Station Name",
                                            "start station latitude": "Start Station Latitude",
                                            "start station longitude": "Start Station Longitude",
                                            "end station id": "End Station ID",
                                            "end station name": "End Station Name",
                                            "end station latitude": "End Station Latitude",
                                            "end station longitude": "End Station Longitude",
                                            "bikeid": "Bike ID",
                                            "usertype": "User Type",
                                            "birth year": "Birth Year",
                                            "gender": "Gender"
                                           })
march2018_df.head()

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
0,816,2018-03-01 02:29:13.7270,2018-03-01 02:42:50.1460,72,W 52 St & 11 Ave,40.767272,-73.993929,379,W 31 St & 7 Ave,40.749156,-73.991600,31413,Subscriber,1973,1
1,235,2018-03-01 05:12:37.0320,2018-03-01 05:16:32.1010,72,W 52 St & 11 Ave,40.767272,-73.993929,478,11 Ave & W 41 St,40.760301,-73.998842,33202,Subscriber,1965,1
2,1250,2018-03-01 05:45:49.9000,2018-03-01 06:06:39.9080,72,W 52 St & 11 Ave,40.767272,-73.993929,3664,North Moore St & Greenwich St,40.720195,-74.010301,26675,Subscriber,1984,1
3,741,2018-03-01 06:54:19.6150,2018-03-01 07:06:40.9790,72,W 52 St & 11 Ave,40.767272,-73.993929,459,W 20 St & 11 Ave,40.746745,-74.007756,31011,Subscriber,1981,1
4,727,2018-03-01 07:08:38.8610,2018-03-01 07:20:46.8500,72,W 52 St & 11 Ave,40.767272,-73.993929,2006,Central Park S & 6 Ave,40.765909,-73.976342,30616,Subscriber,1990,2

In [5]:
# Read June 2018 Citi Bike Data File & Store into Pandas DataFrame
june2018_df = pd.read_csv(june2018, encoding="ISO-8859-1")
june2018_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,569,2018-06-01 01:57:20.5140,2018-06-01 02:06:50.0880,72,W 52 St & 11 Ave,40.767272,-73.993929,173,Broadway & W 49 St,40.760683,-73.984527,21481,Subscriber,1999,1
1,480,2018-06-01 02:02:42.3980,2018-06-01 02:10:43.3540,72,W 52 St & 11 Ave,40.767272,-73.993929,477,W 41 St & 8 Ave,40.756405,-73.990026,19123,Subscriber,1988,1
2,692,2018-06-01 02:04:23.6240,2018-06-01 02:15:55.7470,72,W 52 St & 11 Ave,40.767272,-73.993929,457,Broadway & W 58 St,40.766953,-73.981693,26983,Subscriber,1986,1
3,664,2018-06-01 03:00:55.4610,2018-06-01 03:11:59.9060,72,W 52 St & 11 Ave,40.767272,-73.993929,379,W 31 St & 7 Ave,40.749156,-73.991600,26742,Subscriber,1973,1
4,818,2018-06-01 06:04:54.4270,2018-06-01 06:18:32.6170,72,W 52 St & 11 Ave,40.767272,-73.993929,459,W 20 St & 11 Ave,40.746745,-74.007756,26386,Subscriber,1984,1

In [6]:
june2018_df = june2018_df.rename(columns={"tripduration": "Trip Duration",
                                            "starttime": "Start Time",
                                            "stoptime": "Stop Time",
                                            "start station id": "Start Station ID",
                                            "start station name": "Start Station Name",
                                            "start station latitude": "Start Station Latitude",
                                            "start station longitude": "Start Station Longitude",
                                            "end station id": "End Station ID",
                                            "end station name": "End Station Name",
                                            "end station latitude": "End Station Latitude",
                                            "end station longitude": "End Station Longitude",
                                            "bikeid": "Bike ID",
                                            "usertype": "User Type",
                                            "birth year": "Birth Year",
                                            "gender": "Gender"
                                           })
june2018_df.head()

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
0,569,2018-06-01 01:57:20.5140,2018-06-01 02:06:50.0880,72,W 52 St & 11 Ave,40.767272,-73.993929,173,Broadway & W 49 St,40.760683,-73.984527,21481,Subscriber,1999,1
1,480,2018-06-01 02:02:42.3980,2018-06-01 02:10:43.3540,72,W 52 St & 11 Ave,40.767272,-73.993929,477,W 41 St & 8 Ave,40.756405,-73.990026,19123,Subscriber,1988,1
2,692,2018-06-01 02:04:23.6240,2018-06-01 02:15:55.7470,72,W 52 St & 11 Ave,40.767272,-73.993929,457,Broadway & W 58 St,40.766953,-73.981693,26983,Subscriber,1986,1
3,664,2018-06-01 03:00:55.4610,2018-06-01 03:11:59.9060,72,W 52 St & 11 Ave,40.767272,-73.993929,379,W 31 St & 7 Ave,40.749156,-73.991600,26742,Subscriber,1973,1
4,818,2018-06-01 06:04:54.4270,2018-06-01 06:18:32.6170,72,W 52 St & 11 Ave,40.767272,-73.993929,459,W 20 St & 11 Ave,40.746745,-74.007756,26386,Subscriber,1984,1

In [7]:
# Read September 2018 Citi Bike Data File & Store into Pandas DataFrame
september2018_df = pd.read_csv(september2018, encoding="ISO-8859-1")
september2018_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1635,2018-09-01 00:00:05.2690,2018-09-01 00:27:20.6340,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,25577,Subscriber,1980,1
1,132,2018-09-01 00:00:11.2810,2018-09-01 00:02:23.4810,314.0,Cadman Plaza West & Montague St,40.693830,-73.990539,3242.0,Schermerhorn St & Court St,40.691029,-73.991834,34377,Subscriber,1969,0
2,3337,2018-09-01 00:00:20.6490,2018-09-01 00:55:58.5470,3142.0,1 Ave & E 62 St,40.761227,-73.960940,3384.0,Smith St & 3 St,40.678724,-73.995991,30496,Subscriber,1975,1
3,436,2018-09-01 00:00:21.7460,2018-09-01 00:07:38.5830,308.0,St James Pl & Oliver St,40.713079,-73.998512,3690.0,Park Pl & Church St,40.713342,-74.009355,28866,Subscriber,1984,2
4,8457,2018-09-01 00:00:27.3150,2018-09-01 02:21:25.3080,345.0,W 13 St & 6 Ave,40.736494,-73.997044,380.0,W 4 St & 7 Ave S,40.734011,-74.002939,20943,Customer,1994,1

In [8]:
september2018_df = september2018_df.rename(columns={"tripduration": "Trip Duration",
                                            "starttime": "Start Time",
                                            "stoptime": "Stop Time",
                                            "start station id": "Start Station ID",
                                            "start station name": "Start Station Name",
                                            "start station latitude": "Start Station Latitude",
                                            "start station longitude": "Start Station Longitude",
                                            "end station id": "End Station ID",
                                            "end station name": "End Station Name",
                                            "end station latitude": "End Station Latitude",
                                            "end station longitude": "End Station Longitude",
                                            "bikeid": "Bike ID",
                                            "usertype": "User Type",
                                            "birth year": "Birth Year",
                                            "gender": "Gender"
                                           })
september2018_df.head()

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
0,1635,2018-09-01 00:00:05.2690,2018-09-01 00:27:20.6340,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,25577,Subscriber,1980,1
1,132,2018-09-01 00:00:11.2810,2018-09-01 00:02:23.4810,314.0,Cadman Plaza West & Montague St,40.693830,-73.990539,3242.0,Schermerhorn St & Court St,40.691029,-73.991834,34377,Subscriber,1969,0
2,3337,2018-09-01 00:00:20.6490,2018-09-01 00:55:58.5470,3142.0,1 Ave & E 62 St,40.761227,-73.960940,3384.0,Smith St & 3 St,40.678724,-73.995991,30496,Subscriber,1975,1
3,436,2018-09-01 00:00:21.7460,2018-09-01 00:07:38.5830,308.0,St James Pl & Oliver St,40.713079,-73.998512,3690.0,Park Pl & Church St,40.713342,-74.009355,28866,Subscriber,1984,2
4,8457,2018-09-01 00:00:27.3150,2018-09-01 02:21:25.3080,345.0,W 13 St & 6 Ave,40.736494,-73.997044,380.0,W 4 St & 7 Ave S,40.734011,-74.002939,20943,Customer,1994,1

In [9]:
# Read December 2018 Citi Bike Data File & Store into Pandas DataFrame
december2018_df = pd.read_csv(december2018, encoding="ISO-8859-1")
december2018_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,689,2018-12-01 00:00:04.3020,2018-12-01 00:11:33.8460,3359.0,E 68 St & Madison Ave,40.769157,-73.967035,164.0,E 47 St & 2 Ave,40.753231,-73.970325,35033,Subscriber,1989,1
1,204,2018-12-01 00:00:05.5330,2018-12-01 00:03:30.5230,3504.0,E 123 St & Lexington Ave,40.802926,-73.937900,3490.0,E 116 St & 2 Ave,40.796879,-73.937261,20501,Subscriber,1966,1
2,316,2018-12-01 00:00:10.2330,2018-12-01 00:05:27.2030,270.0,Adelphi St & Myrtle Ave,40.693083,-73.971789,243.0,Fulton St & Rockwell Pl,40.688226,-73.979382,18386,Subscriber,1984,1
3,726,2018-12-01 00:00:21.9570,2018-12-01 00:12:28.1830,495.0,W 47 St & 10 Ave,40.762699,-73.993012,3660.0,W 16 St & 8 Ave,40.741022,-74.001385,27616,Subscriber,1983,1
4,397,2018-12-01 00:00:29.6320,2018-12-01 00:07:07.4460,473.0,Rivington St & Chrystie St,40.721101,-73.991925,3467.0,W Broadway & Spring Street,40.724947,-74.001659,35096,Subscriber,1976,1

In [10]:
december2018_df = december2018_df.rename(columns={"tripduration": "Trip Duration",
                                            "starttime": "Start Time",
                                            "stoptime": "Stop Time",
                                            "start station id": "Start Station ID",
                                            "start station name": "Start Station Name",
                                            "start station latitude": "Start Station Latitude",
                                            "start station longitude": "Start Station Longitude",
                                            "end station id": "End Station ID",
                                            "end station name": "End Station Name",
                                            "end station latitude": "End Station Latitude",
                                            "end station longitude": "End Station Longitude",
                                            "bikeid": "Bike ID",
                                            "usertype": "User Type",
                                            "birth year": "Birth Year",
                                            "gender": "Gender"
                                           })
december2018_df.head()

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
0,689,2018-12-01 00:00:04.3020,2018-12-01 00:11:33.8460,3359.0,E 68 St & Madison Ave,40.769157,-73.967035,164.0,E 47 St & 2 Ave,40.753231,-73.970325,35033,Subscriber,1989,1
1,204,2018-12-01 00:00:05.5330,2018-12-01 00:03:30.5230,3504.0,E 123 St & Lexington Ave,40.802926,-73.937900,3490.0,E 116 St & 2 Ave,40.796879,-73.937261,20501,Subscriber,1966,1
2,316,2018-12-01 00:00:10.2330,2018-12-01 00:05:27.2030,270.0,Adelphi St & Myrtle Ave,40.693083,-73.971789,243.0,Fulton St & Rockwell Pl,40.688226,-73.979382,18386,Subscriber,1984,1
3,726,2018-12-01 00:00:21.9570,2018-12-01 00:12:28.1830,495.0,W 47 St & 10 Ave,40.762699,-73.993012,3660.0,W 16 St & 8 Ave,40.741022,-74.001385,27616,Subscriber,1983,1
4,397,2018-12-01 00:00:29.6320,2018-12-01 00:07:07.4460,473.0,Rivington St & Chrystie St,40.721101,-73.991925,3467.0,W Broadway & Spring Street,40.724947,-74.001659,35096,Subscriber,1976,1

In [11]:
# Combine All 2018 DataFrames
combined2018_df = march2018_df.append([june2018_df, september2018_df, december2018_df], ignore_index=True)
combined2018_df

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
0,816,2018-03-01 02:29:13.7270,2018-03-01 02:42:50.1460,72.0,W 52 St & 11 Ave,40.767272,-73.993929,379.0,W 31 St & 7 Ave,40.749156,-73.991600,31413,Subscriber,1973,1
1,235,2018-03-01 05:12:37.0320,2018-03-01 05:16:32.1010,72.0,W 52 St & 11 Ave,40.767272,-73.993929,478.0,11 Ave & W 41 St,40.760301,-73.998842,33202,Subscriber,1965,1
2,1250,2018-03-01 05:45:49.9000,2018-03-01 06:06:39.9080,72.0,W 52 St & 11 Ave,40.767272,-73.993929,3664.0,North Moore St & Greenwich St,40.720195,-74.010301,26675,Subscriber,1984,1
3,741,2018-03-01 06:54:19.6150,2018-03-01 07:06:40.9790,72.0,W 52 St & 11 Ave,40.767272,-73.993929,459.0,W 20 St & 11 Ave,40.746745,-74.007756,31011,Subscriber,1981,1
4,727,2018-03-01 07:08:38.8610,2018-03-01 07:20:46.8500,72.0,W 52 St & 11 Ave,40.767272,-73.993929,2006.0,Central Park S & 6 Ave,40.765909,-73.976342,30616,Subscriber,1990,2
5,341,2018-03-01 07:22:50.3340,2018-03-01 07:28:31.9040,72.0,W 52 St & 11 Ave,40.767272,-73.993929,479.0,9 Ave & W 45 St,40.760193,-73.991255,33112,Subscriber,1974,1
6,697,2018-03-01 07:22:51.8030,2018-03-01 07:34:29.2430,72.0,W 52 St & 11 Ave,40.767272,-73.993929,520.0,W 52 St & 5 Ave,40.759923,-73.976485,19139,Subscriber,1953,1
7,407,2018-03-01 07:33:26.7530,2018-03-01 07:40:14.1560,72.0,W 52 St & 11 Ave,40.767272,-73.993929,173.0,Broadway & W 49 St,40.760683,-73.984527,27960,Subscriber,1987,1
8,978,2018-03-01 07:45:31.9580,2018-03-01 08:01:50.6420,72.0,W 52 St & 11 Ave,40.767272,-73.993929,498.0,Broadway & W 32 St,40.748549,-73.988084,24956,Subscriber,1980,2
9,396,2018-03-01 07:46:59.3130,2018-03-01 07:53:35.5640,72.0,W 52 St & 11 Ave,40.767272,-73.993929,173.0,Broadway & W 49 St,40.760683,-73.984527,16765,Subscriber,1983,1
10,284,2018-03-01 07:48:39.7560,2018-03-01 07:53:24.6560,72.0,W 52 St & 11 Ave,40.767272,-73.993929,514.0,12 Ave & W 40 St,40.760875,-74.002777,25864,Subscriber,1991,2
11,1246,2018-03-01 08:19:17.5790,2018-03-01 08:40:03.9350,72.0,W 52 St & 11 Ave,40.767272,-73.993929,347.0,Greenwich St & W Houston St,40.728846,-74.008591,31053,Subscriber,1982,1
12,78,2018-03-01 08:27:09.2360,2018-03-01 08:28:27.2780,72.0,W 52 St & 11 Ave,40.767272,-73.993929,72.0,W 52 St & 11 Ave,40.767272,-73.993929,18350,Subscriber,1984,1
13,1304,2018-03-01 08:28:59.6670,2018-03-01 08:50:44.2980,72.0,W 52 St & 11 Ave,40.767272,-73.993929,336.0,Sullivan St & Washington Sq,40.730477,-73.999061,21466,Subscriber,1988,2
14,1271,2018-03-01 08:31:30.3630,2018-03-01 08:52:41.5290,72.0,W 52 St & 11 Ave,40.767272,-73.993929,328.0,Watts St & Greenwich St,40.724055,-74.009660,32956,Subscriber,1984,1
15,756,2018-03-01 08:31:43.9830,2018-03-01 08:44:20.8510,72.0,W 52 St & 11 Ave,40.767272,-73.993929,484.0,W 44 St & 5 Ave,40.755003,-73.980144,19366,Subscriber,1960,2
16,699,2018-03-01 08:38:19.6500,2018-03-01 08:49:58.9280,72.0,W 52 St & 11 Ave,40.767272,-73.993929,3235.0,E 41 St & Madison Ave,40.752165,-73.979922,32803,Subscriber,1956,1
17,317,2018-03-01 08:45:18.2830,2018-03-01 08:50:36.1900,72.0,W 52 St & 11 Ave,40.767272,-73.993929,514.0,12 Ave & W 40 St,40.760875,-74.002777,33336,Subscriber,1990,1
18,474,2018-03-01 08:47:38.2860,2018-03-01 08:55:32.4200,72.0,W 52 St & 11 Ave,40.767272,-73.993929,458.0,11 Ave & W 27 St,40.751396,-74.005226,17877,Subscriber,1982,1
19,450,2018-03-01 08:47:38.7210,2018-03-01 08:55:09.2340,72.0,W 52 St & 11 Ave,40.767272,-73.993929,523.0,W 38 St & 8 Ave,40.754666,-73.991382,18101,Subscriber,1989,1
20,678,2018-03-01 08:54:20.3590,2018-03-01 09:05:38.7380,72.0,W 52 St & 11 Ave,40.767272,-73.993929,3224.0,W 13 St & Hudson St,40.739974,-74.005139,28109,Subscriber,1973,1
21,1113,2018-03-01 09:10:38.1740,2018-03-01 09:29:12.1260,72.0,W 52 St & 11 Ave,40.767272,-73.993929,284.0,Greenwich Ave & 8 Ave,40.739017,-74.002638,31990,Subscriber,1992,1
22,1101,2018-03-01 09:10:47.4480,2018-03-01 09:29:09.1870,72.0,W 52 St & 11 Ave,40.767272,-73.993929,284.0,Greenwich Ave & 8 Ave,40.739017,-74.002638,18350,Subscriber,1992,1
23,770,2018-03-01 09:44:08.7150,2018-03-01 09:56:59.4530,72.0,W 52 St & 11 Ave,40.767272,-73.993929,442.0,W 27 St & 7 Ave,40.746647,-73.993915,32635,Subscriber,1984,1
24,588,2018-03-01 09:56:24.6780,2018-03-01 10:06:13.4980,72.0,W 52 St & 11 Ave,40.767272,-73.993929,459.0,W 20 St & 11 Ave,40.746745,-74.007756,32313,Subscriber,1989,1
25,357,2018-03-01 10:13:16.4520,2018-03-01 10:19:14.2300,72.0,W 52 St & 11 Ave,40.767272,-73.993929,477.0,W 41 St & 8 Ave,40.756405,-73.990026,29005,Subscriber,1986,1
26,935,2018-03-01 10:34:25.7340,2018-03-01 10:50:01.3550,72.0,W 52 St & 11 Ave,40.767272,-73.993929,466.0,W 25 St & 6 Ave,40.743954,-73.991449,25931,Subscriber,1967,1
27,673,2018-03-01 10:44:25.2350,2018-03-01 10:55:38.9930,72.0,W 52 St & 11 Ave,40.767272,-73.993929,3635.0,W 36 St & 9 Ave,40.754623,-73.995168,29168,Subscriber,1981,1
28,751,2018-03-01 10:54:55.3200,2018-03-01 11:07:27.2220,72.0,W 52 St & 11 Ave,40.767272,-73.993929,3175.0,W 70 St & Amsterdam Ave,40.777480,-73.982886,17381,Subscriber,1966,2
29,1441,2018-03-01 11:46:12.1620,2018-03-01 12:10:13.7340,72.0,W 52 St & 11 Ave,40.767272,-73.993929,426.0,West St & Chambers St,40.717548,-74.013221,16021,Subscriber,1992,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5824134,206,2018-12-31 23:30:09.5760,2018-12-31 23:33:36.5100,390.0,Duffield St & Willoughby St,40.692216,-73.984284,243.0,Fulton St & Rockwell Pl,40.688226,-73.979382,27440,Subscriber,1985,2
5824135,924,2018-12-31 23:30:41.7490,2018-12-31 23:46:06.7030,446.0,W 24 St & 7 Ave,40.744876,-73.995299,516.0,E 47 St & 1 Ave,40.752069,-73.967844,34663,Subscriber,1980,1
5824136,426,2018-12-31 23:32:07.9720,2018-12-31 23:39:14.3750,368.0,Carmine St & 6 Ave,40.730386,-74.002150,146.0,Hudson St & Reade St,40.716250,-74.009106,34329,Subscriber,1999,1
5824137,247,2018-12-31 23:32:26.2510,2018-12-31 23:36:34.0940,383.0,Greenwich Ave & Charles St,40.735238,-74.000271,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,32671,Subscriber,1989,1
5824138,282,2018-12-31 23:32:30.8410,2018-12-31 23:37:13.3520,383.0,Greenwich Ave & Charles St,40.735238,-74.000271,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,15624,Subscriber,1988,1
5824139,245,2018-12-31 23:35:10.8400,2018-12-31 23:39:16.6350,3136.0,5 Ave & E 63 St,40.766368,-73.971518,3137.0,5 Ave & E 73 St,40.772828,-73.966853,26633,Subscriber,1961,1
5824140,516,2018-12-31 23:35:37.7230,2018-12-31 23:44:14.4130,128.0,MacDougal St & Prince St,40.727103,-74.002971,308.0,St James Pl & Oliver St,40.713079,-73.998512,19088,Subscriber,1984,1
5824141,588,2018-12-31 23:36:25.3260,2018-12-31 23:46:13.6530,3397.0,Court St & Nelson St,40.676395,-73.998699,143.0,Clinton St & Joralemon St,40.692395,-73.993379,15107,Subscriber,1964,1
5824142,306,2018-12-31 23:36:51.0920,2018-12-31 23:41:57.3660,82.0,St James Pl & Pearl St,40.711174,-74.000165,340.0,Madison St & Clinton St,40.712690,-73.987763,15864,Subscriber,1995,1
5824143,927,2018-12-31 23:37:03.8570,2018-12-31 23:52:31.7830,3151.0,E 81 St & York Ave,40.772838,-73.949892,3137.0,5 Ave & E 73 St,40.772828,-73.966853,35203,Customer,1998,1
5824144,94,2018-12-31 23:37:27.7690,2018-12-31 23:39:02.0710,360.0,William St & Pine St,40.707179,-74.008873,376.0,John St & William St,40.708621,-74.007222,31001,Subscriber,1991,1
5824145,1161,2018-12-31 23:38:29.4360,2018-12-31 23:57:51.3750,495.0,W 47 St & 10 Ave,40.762699,-73.993012,281.0,Grand Army Plaza & Central Park S,40.764397,-73.973715,16078,Subscriber,1969,0
5824146,1015,2018-12-31 23:39:10.7270,2018-12-31 23:56:06.6920,379.0,W 31 St & 7 Ave,40.749156,-73.991600,301.0,E 2 St & Avenue B,40.722174,-73.983688,34170,Subscriber,1985,1
5824147,776,2018-12-31 23:41:17.7150,2018-12-31 23:54:13.9450,532.0,S 5 Pl & S 5 St,40.710451,-73.960876,307.0,Canal St & Rutgers St,40.714275,-73.989900,34093,Subscriber,1988,2
5824148,588,2018-12-31 23:41:14.4590,2018-12-31 23:51:02.5500,195.0,Liberty St & Broadway,40.709056,-74.010434,534.0,Water - Whitehall Plaza,40.702551,-74.012723,35081,Subscriber,1980,1
5824149,71,2018-12-31 23:42:57.9190,2018-12-31 23:44:09.2080,3367.0,5 Ave & E 103 St,40.792255,-73.952499,3367.0,5 Ave & E 103 St,40.792255,-73.952499,27026,Subscriber,1955,1
5824150,217,2018-12-31 23:43:10.0890,2018-12-31 23:46:47.4740,314.0,Cadman Plaza West & Montague St,40.693830,-73.990539,391.0,Clark St & Henry St,40.697601,-73.993446,27452,Subscriber,1965,1
5824151,385,2018-12-31 23:45:45.7440,2018-12-31 23:52:10.9330,3429.0,Hanson Pl & Ashland Pl,40.685068,-73.977908,3637.0,Fulton St & Waverly Ave,40.683239,-73.965996,33086,Subscriber,1973,1
5824152,651,2018-12-31 23:46:44.4210,2018-12-31 23:57:35.9100,3295.0,Central Park W & W 96 St,40.791270,-73.964839,3165.0,Central Park West & W 72 St,40.775794,-73.976206,32449,Subscriber,1969,0
5824153,620,2018-12-31 23:47:10.2080,2018-12-31 23:57:30.6020,3295.0,Central Park W & W 96 St,40.791270,-73.964839,3165.0,Central Park West & W 72 St,40.775794,-73.976206,15699,Customer,1989,2
5824154,798,2018-12-31 23:49:37.0590,2019-01-01 00:02:55.1640,518.0,E 39 St & 2 Ave,40.747804,-73.973442,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,35603,Subscriber,1982,1
5824155,312,2018-12-31 23:49:43.9520,2018-12-31 23:54:56.2510,3166.0,Riverside Dr & W 72 St,40.780578,-73.985624,3164.0,Columbus Ave & W 72 St,40.777057,-73.978985,27419,Subscriber,1960,1
5824156,165,2018-12-31 23:50:34.6070,2018-12-31 23:53:20.5830,498.0,Broadway & W 32 St,40.748549,-73.988084,472.0,E 32 St & Park Ave,40.745712,-73.981948,20190,Subscriber,1994,2
5824157,1027,2018-12-31 23:51:13.9220,2019-01-01 00:08:21.7900,423.0,W 54 St & 9 Ave,40.765849,-73.986905,285.0,Broadway & E 14 St,40.734546,-73.990741,28510,Subscriber,1981,1
5824158,174,2018-12-31 23:53:59.0720,2018-12-31 23:56:53.4750,260.0,Broad St & Bridge St,40.703652,-74.011678,260.0,Broad St & Bridge St,40.703652,-74.011678,33887,Subscriber,1980,1
5824159,734,2018-12-31 23:55:06.9910,2019-01-01 00:07:21.2300,336.0,Sullivan St & Washington Sq,40.730477,-73.999061,379.0,W 31 St & 7 Ave,40.749156,-73.991600,27111,Subscriber,1986,1
5824160,2551,2018-12-31 23:55:44.3070,2019-01-01 00:38:15.7820,3320.0,Central Park West & W 100 St,40.794067,-73.962868,2006.0,Central Park S & 6 Ave,40.765909,-73.976342,16390,Customer,1969,0
5824161,2376,2018-12-31 23:56:52.8500,2019-01-01 00:36:29.2860,427.0,Bus Slip & State St,40.701907,-74.013942,259.0,South St & Whitehall St,40.701221,-74.012342,34398,Subscriber,1979,1
5824162,2758,2018-12-31 23:58:29.2120,2019-01-01 00:44:27.5170,3320.0,Central Park West & W 100 St,40.794067,-73.962868,281.0,Grand Army Plaza & Central Park S,40.764397,-73.973715,30818,Customer,1969,0
5824163,2459,2018-12-31 23:59:51.0850,2019-01-01 00:40:50.8800,128.0,MacDougal St & Prince St,40.727103,-74.002971,402.0,Broadway & E 22 St,40.740343,-73.989551,34775,Subscriber,1996,2

In [12]:
len(combined2018_df)

5824164

In [ ]:
# Save Combined DataFrames to CSV
combined2018_df.to_csv("2018-citibike-tripdata.csv", index=False, header=True)